site_name: Sayer
site_description: The click running on steroids.
site_url: https://sayer.tarsild.io

theme:
  name: "material"
  custom_dir: docs/overrides
  language: en
  palette:
    - scheme: "amber"
      primary: "red"
      accent: "lime"
      media: "(prefers-color-scheme: light)"
      toggle:
            icon: "material/lightbulb"
            name: "Switch to dark mode"
    - scheme: "amber"
      media: "(prefers-color-scheme: dark)"
      primary: "lime"
      accent: "red"
      toggle:
            icon: "material/lightbulb-outline"
            name: "Switch to light mode"
  favicon: statics/images/favicon.ico
  logo: statics/images/logo-white.svg
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.code.select
    - navigation.indexes
    - navigation.path
    - navigation.tabs

repo_name: tarsil/sayer
repo_url: https://github.com/tarsil/sayer
edit_uri: ""
plugins:
  - search
  - meta-descriptions:
      export_csv: false
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
      trim: false

nav:
  - Introduction: "index.md"
  - Contributing: "contributing.md"
  - Sponsorship: "sponsorship.md"
  - Release Notes: "release-notes.md"
markdown_extensions:
  - toc:
      permalink: true
  - mdx_include:
      base_path: docs
  - admonition
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  alternate:
    - link: /
      name: English
      lang: en
