#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi
if [ -d 'site' ] ; then
    rm -r site
fi
if [ -d 'htmlcov' ] ; then
    rm -r htmlcov
fi
if [ -d 'sayer.egg-info' ] ; then
    rm -r sayer.egg-info
fi
if [ -d '.hypothesis' ] ; then
    rm -r .hypothesis
fi
if [ -d '.mypy_cache' ] ; then
    rm -r .mypy_cache
fi
if [ -d '.ty_cache' ] ; then
    rm -r .ty_cache
fi
if [ -d '.pytest_cache' ] ; then
    rm -r .pytest_cache
fi
if [ -d '.ruff_cache' ] ; then
    rm -r .ruff_cache
fi
if [ -d '.cache' ] ; then
    rm -r .cache
fi
if [ -d 'docs/generated' ] ; then
    rm -r docs/generated
fi

find sayer -type f -name "*.py[co]" -delete
find sayer -type d -name __pycache__ -delete
